### ISSUE TITLE
move help-patches to doc/7.stuff/patching/

### ISSUE THREAD

**Issue by umlaeute** [HenriAugusto/pure-data#4]
having a folder for only a single help-patch seems a bit excessive...

i suggest to:
- break the help-patch into multiple files
- rename the containing directory to something more general, like `patching`, where we can also document standard editing features (starting with "edit-mode  vs performance-mode") and things like " intelligent patching")

**Comment by HenriAugusto** [comment]
done in adcbf736618d0a8428ffc3a841e817714a4b7ab8
