### ISSUE TITLE
magnetic connector attempts to connect to unconnectable things

### ISSUE THREAD

**Issue by umlaeute** [HenriAugusto/pure-data#5]
btw, there's another small bug with the *magnetic connector*: if i open the help-subpatch, select the `[noise~]` object, go into keyboard-navigation mode and hit <kbd>g</kbd> **8** times, i get an error on the Pd-console:
> magnetic_connector 3 0 0 0 (noise~->text) connection failed

**Comment by HenriAugusto** [comment]
fixed e04adc2dbe1a4991ac85d646f127d9537b302659
